### ISSUE TITLE
./log4jscan.sh: 104: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by WKoster** [intezer/log4jscan#2]
Like it says... I get a:

./log4jscan.sh: 104: Syntax error: word unexpected (expecting ")")

**Comment by doronshemtov** [comment]
Hi,
Thanks for the feedback.

Seems like the bash version you are using is not supporting arrays.

what version do you use?

lines 100-105 (of the current version - v1.0.1) are used to avoid from printing info about files already found during the scan.

You can try to remove them, the scan itself won’t be affected, but you might see the same result multiple times.

**Comment by WKoster** [comment]
$ /bin/bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

Should be pretty standard/up-to-date

Anyways if I remove lines 100-105 I get:

./log4jscan.sh: 67: Bad substitution

**Comment by doronshemtov** [comment]
Hi,

I have managed to reproduce the errors you got by executing the script like this: `sudo sh ./log4jscan.sh`
Is it possible that the script is not being executed by bash in your environment?

Could you please share how you execute the script?
Also, could you please share the output of `ls -l /bin/bash`?

**Comment by WKoster** [comment]
OMG.. you're right. I AM ashamed.. .thank you for your support.

**Comment by doronshemtov** [comment]
No worries :)

Feel free to reach out if you encounter additional issues.
