### ISSUE TITLE
readlink sometimes returns (deleted) at the end of line

### ISSUE THREAD

**Issue by bostjank** [intezer/log4jscan#5]
Found out that scan does not find all cases. I have running process, but scanner does not find them. Issue is that for this processes readlink returned:
`....lib/log4j-core-2.15.0.jar (deleted)`
That is later skipped up by filter:
`# skip non jar files
       		if [[ "$link_target" != *.jar ]]; then
			continue
		fi
`
I do not know enough about linux system, that I could explain why readlink returned this. But the processes are running normally.

**Comment by doronshemtov** [comment]
Hi,
Thanks for bringing it up.

It means that the file was removed while the process is still running.

I will add support for such case.

**Comment by bostjank** [comment]
This works for me: 
```
link_read=$(readlink ${line}) 
link_target=${link_read% \(deleted\)}
```
But please review and maybe find a better way.

**Comment by doronshemtov** [comment]
Hi,

Thanks again for reporting this.

I have released a new version that supports this case:
https://github.com/intezer/log4jscan/releases/tag/v1.2.0

FYI, the new version can scan the jar file and extract the log4j version even if it is deleted.
We are able to achieve this by accessing the file via the open file descriptor.

**Comment by doronshemtov** [comment]
I’m closing the issue, feel free to reach out if you encounter an issue or if you have any question 😊
